# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "XVIII Symposium of Mexican Studies and Students in the UK"
email: "symposium.mxuk.2020@gmail.com"
description: "XVIII Symposium of Mexican Studies and Students in the UK"
baseurl: "/xviii"
url: "http://symposiumMXUK.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Mexican Student Community in Nottingham"
organizerAlternateName: "University of Nottingham Mexican Society"
organizerDescription: "Open and volunteer community of Mexican and International students and researchers."
organizerEmail: "symposium.mxuk.2020@gmail.com"
organizerLogo: "/img/sections-background/logo.jpg"
#organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "symposium mx uk, symposium mexican studies and students, mexico, uk, symposium xviii, symposium 2020"
twitterAccount: "@MX_Symposium"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
#c4pUrl: "http://bit.ly/dfua-c4p"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 #- {permalink: "/blog/", text: "Blog"}
 #- {permalink: "/schedule/", text: "Schedule"}
 #- {permalink: "/speakers/", text: "Speakers"}
 #- {permalink: "/team/", text: "Team"}
 #- {permalink: "/logistics/", text: "Logistics"}
 #- {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 #- {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 #- {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "nottingham-intro.jpg"
heroTitle: "XVIII Symposium of Mexican <typeout> in the UK"
eventDate: "8-10 July 2020"
typeoutTextValues: '"Students", "Studies"'
typeoutFallback: "synergy"
heroButtons:
 #- {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}
 #- {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About the Symposium"
aboutBlock:
 - {title: "Presentations", image: "conference.jpg", text: "testo aqui" }
 - {title: "Posters", image: "workshop.jpg", text: "testo aca" }
 - {title: "Networking", image: "hackathon.jpg", text: "blah bleh blah" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
#locationBlockTitle: "Location"
#eventLocationName: "University of Nottingham"
#eventLocationLink: "https://www.nottingham.ac.uk/"
#eventStreetAddress: "22 Teatral'na St"
#eventAddressLocality: "Lviv"
#eventAddressLocalityRegion: "Lvivska"
#eventPostalCode: "79000"
#eventAddressCountry: "Ukraine"
#eventStartTime: "2014-10-25T10:00"
#eventDoorTime: "09:00"
#eventEndTime: "2014-10-25T20:00"
#eventPlaceCoordinates: "49.843237, 24.028751"
#mapCenterCoordinates: "49.842537, 24.025701"
#mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "University of Nottingham"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "symposiumMXuk2020"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
#partnersC4sponsorsButton: "Become a sponsor"


# Footer
socialLinks:
 - {link: "https://twitter.com/MX_Symposium", icon: "twitter"}
 #- {link: "https://facebook.com/GDGLviv", icon: "facebook"}
footerBlocks:
 #-
  #title: "Links"
  #links:
   #- {link: "http://gdg.org.ua", text: "GDG.org.ua"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:symposium.mxuk.2020@gmail.com", text: "symposium.mxuk.2020@gmail.com"}


# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
