# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "XVIII Symposium of Mexican Studies and Students in the UK"
email: "symposium.mxuk.2020@gmail.com"
description: "XVIII Symposium of Mexican Studies and Students in the UK"
baseurl: "/xviii"
url: "http://symposiumMXUK.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-158659681-1"
googleAnalyticsSiteUrl: "symposiummx.com"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Mexican Student Community in Nottingham"
organizerAlternateName: "University of Nottingham Mexican Society"
organizerDescription: "Open and volunteer community of Mexican and International students and researchers."
organizerEmail: "symposium.mxuk.2020@gmail.com"
organizerLogo: "/img/sections-background/logo.jpg"
#organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "symposium mx uk, symposium mexican studies and students, mexico, uk, symposium xviii, symposium 2020"
twitterAccount: "@MX_Symposium"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
abstractTemplate: "/assets/Abstract_template_XVIII_Mexican_Symposium.docx"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/about/", text: "About"}
 - {permalink: "/blog/", text: "Blog"}
 #- {permalink: "/schedule/", text: "Schedule"}
 #- {permalink: "/speakers/", text: "Speakers"}
 #- {permalink: "/logistics/", text: "Logistics"}
 #- {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 #- {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 #- {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "trent_building_3.jpg"
heroTitle: "XVIII Symposium of Mexican Studies and Students in the UK"
eventDate: "1-2 July 2021, (Online) from Nottingham UK"
#typeoutTextValues: '"", "Students", "Studies"'
#typeoutFallback: "synergy"
heroButtons:
 - {permalink: "/blog/", text: "Latest News"}
 - {permalink: "/#tickets", text: "REGISTER"}


# About Block
aboutTitle: "About the Symposium"
aboutBlock:
 - {title: "Presentations", image: "presentations.jpg", text: "Two days of keynote presentations from outstanding leaders in relevant fields, as well as academic presentations and poster sessions of accepted submissions." }
 - {title: "Panels", image: "panels.jpg", text: "This year's edition theme is “Synergy, the link to the future”, therefore some abstracts will be selected for panel discussions during the conference. " }
 - {title: "Networking", image: "networking.jpg", text: "This event brings together people from different areas or fields based in Mexico and all over the UK, enabling relevant academic and professional connections." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "150", specialCharacter: "+", info: "attendees", detail: "from Mexico and the UK"}
 - {count: "2", specialCharacter: "", info: "days", detail: "of presentations, panels and networking"}
 - {count: "15", specialCharacter: "+", info: "keynote talks", detail: "from outstanding leaders in relevant fields"}
 - {count: "4", specialCharacter: "", info: "multi-disciplinary categories", detail: "STEM, Humanities, Business & Politics"}

# Latest News Block
latestNewsTitle: "Latest news"

# Tickets Block
ticketsTitle: "Registration"
ticketsInfo: "Tickets grant access to all conference sessions."
ticketsOffers:
 -
  name: "Attendees"
  price: "FREE"
  priceCurrency: ""
  buyButtonLink: "https://www.eventbrite.com/e/xviii-symposium-of-mexican-studies-and-students-in-the-uk-tickets-156142168429"
  buyButtonText: "Register Now"
  ticketContentList: ["1 or 2 days of Symposium", "Access to all sessions", "Enter code if you are presenting"]

# Rockstar Speakers Block
#rockstarSpeakersImage: "rockstar-speakers.jpg"
#rockstarSpeakersCount: 4
#rockstarSpeakersTitle: "Rockstar speakers"
#rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "University of Nottingham"
eventLocationLink: "https://www.nottingham.ac.uk/"
eventStreetAddress: "University Park Campus"
eventAddressLocality: "Nottingham"
eventAddressLocalityRegion: "Nottinghamshire"
eventPostalCode: "NG7 2RD"
eventAddressCountry: "United Kingdom"
#eventStartTime: "2020-07-208T16:00"
#eventDoorTime: "09:00"
#eventEndTime: "2020-07-10T18:00"
eventPlaceCoordinates: "49.843237, 24.028751"
mapCenterCoordinates: "49.842537, 24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
#venueBlockTitle: "University of Nottingham"
#venueBigImage: "venue_0.jpg"
#venueSmallImage1: "venue_1.jpg"
#venueSmallImage2: "venue_2.jpg"
#venueSmallImage3: "venue_3.jpg"
#venueTitle: "Kinopalace Cinema"
#venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "hugh-stewart-hall.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "StayAtHome"
#twitterFeed: ""

# Partners Block
#organizersTitle: "Organizers"
#partnersTitle: "Partners"
#partnersC4sponsorsButton: "Become a sponsor"


# Footer
socialLinks:
 - {link: "https://twitter.com/MX_Symposium", icon: "twitter"}
 - {link: "https://www.facebook.com/symposiumMXinUK/", icon: "facebook"}
footerBlocks:
 -
  title: "Contact"
  links:
   - {link: "mailto:symposium.mxuk.2020@gmail.com", text: "symposium.mxuk.2020@gmail.com"}
 -
  title: "Information"
  links:
   - {permalink: "/faq/", text: "Frequently Asked Questions"}



# Blog
blogTitle: "Latest news"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "The Symposium of Mexican Studies and Students in the UK is a space for scientific and academic dissemination intended for students, researchers, research centres and companies interested in the scientific, technological and multidisciplinary development of Mexico and Latin America. This year, the symposium will be hosted by the University of Nottingham. Our main theme is 'Synergy, the Link to the Future'. The Oxford dictionary defines the word “synergy” as the collaboration of two or more agents to produce a combined effect greater than the sum of their separate effects. The organising committee decided to use this word to highlight the importance of the interaction between the disciplines. We are stronger together and our knowledge works better when we share it, discuss it, integrate it and apply it. Therefore, we think that indeed, working together (in synergy) is the right path to a better future.
"
